version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:8002
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_ENABLE_STATIC_SERVING=true
    networks:
      - write2solve-network

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./app:/app
    depends_on:
      - ocr_service
    restart: unless-stopped
    environment:
      - OCR_SERVICE_URL=http://ocr_service:8001
      - PYTHONUNBUFFERED=1
    networks:
      - write2solve-network

  ocr_service:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
    restart: unless-stopped
    environment:
      - MODEL_PATH=/app/services/models
      - OCR_MODEL_PATH=facebook/nougat-base
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "services.ocr_api:app", "--host", "0.0.0.0", "--port", "8001"]
    networks:
      - write2solve-network

networks:
  write2solve-network:
    driver: bridge

volumes:
  frontend-data:
  backend-data:
  ocr-data: 

